# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{numb}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Run Paint Run Run"]
  s.date = %q{2009-08-17}
  s.email = %q{runrun@runpaint.org}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/numb.rb",
     "lib/numb/abundant.rb",
     "lib/numb/achilles.rb",
     "lib/numb/automorphic.rb",
     "lib/numb/carol.rb",
     "lib/numb/deficient.rb",
     "lib/numb/dihedral_prime.rb",
     "lib/numb/dudeney.rb",
     "lib/numb/economical.rb",
     "lib/numb/emrip.rb",
     "lib/numb/equidigital.rb",
     "lib/numb/extravagant.rb",
     "lib/numb/factorion.rb",
     "lib/numb/frugal.rb",
     "lib/numb/happy.rb",
     "lib/numb/harshad.rb",
     "lib/numb/hilbert.rb",
     "lib/numb/hyperperfect.rb",
     "lib/numb/impolite.rb",
     "lib/numb/kaprekar.rb",
     "lib/numb/keith.rb",
     "lib/numb/kynea.rb",
     "lib/numb/mms_pair.rb",
     "lib/numb/mobius.rb",
     "lib/numb/narcissistic.rb",
     "lib/numb/nivenmorphic.rb",
     "lib/numb/parasitic.rb",
     "lib/numb/perfect.rb",
     "lib/numb/perfect_power.rb",
     "lib/numb/polite.rb",
     "lib/numb/polydivisible.rb",
     "lib/numb/powerful.rb",
     "lib/numb/practical.rb",
     "lib/numb/self.rb",
     "lib/numb/self_descriptive.rb",
     "lib/numb/semi_perfect.rb",
     "lib/numb/semiprime.rb",
     "lib/numb/smarandache_wellin.rb",
     "lib/numb/smith.rb",
     "lib/numb/sphenic.rb",
     "lib/numb/square.rb",
     "lib/numb/square_free.rb",
     "lib/numb/triangular.rb",
     "lib/numb/trimorphic.rb",
     "lib/numb/undulating.rb",
     "lib/numb/vampire.rb",
     "lib/numb/weird.rb",
     "spec/abundant_spec.rb",
     "spec/achilles_spec.rb",
     "spec/automorphic_spec.rb",
     "spec/carol_spec.rb",
     "spec/deficient_spec.rb",
     "spec/digital_sum_spec.rb",
     "spec/dihedral_prime_spec.rb",
     "spec/dudeney_spec.rb",
     "spec/economical_spec.rb",
     "spec/emrip_spec.rb",
     "spec/equidigital_spec.rb",
     "spec/extravagant_spec.rb",
     "spec/factor_spec.rb",
     "spec/factorion_spec.rb",
     "spec/frugal_spec.rb",
     "spec/happy_spec.rb",
     "spec/harshad_spec.rb",
     "spec/hilbert_spec.rb",
     "spec/hyperperfect_spec.rb",
     "spec/kaprekar_spec.rb",
     "spec/keith_spec.rb",
     "spec/kynea_spec.rb",
     "spec/maris_mcgwire_sosa_pair_spec.rb",
     "spec/mobius_spec.rb",
     "spec/narcissistic_spec.rb",
     "spec/nivenmorphic_spec.rb",
     "spec/number_of_distinct_prime_factors_spec.rb",
     "spec/number_of_prime_factors_spec.rb",
     "spec/parasitic_spec.rb",
     "spec/perfect_power_spec.rb",
     "spec/perfect_spec.rb",
     "spec/polite_spec.rb",
     "spec/politeness_spec.rb",
     "spec/polydivisible_spec.rb",
     "spec/powerful_spec.rb",
     "spec/practical_spec.rb",
     "spec/self_descriptive_spec.rb",
     "spec/self_spec.rb",
     "spec/semi_perfect_spec.rb",
     "spec/semiprime_spec.rb",
     "spec/smarandache_wellin_spec.rb",
     "spec/smith_spec.rb",
     "spec/spec_helper.rb",
     "spec/sphenic_spec.rb",
     "spec/square_free_spec.rb",
     "spec/square_spec.rb",
     "spec/triangular_spec.rb",
     "spec/trimorphic_spec.rb",
     "spec/undulating_spec.rb",
     "spec/vampire_spec.rb",
     "spec/weird_spec.rb"
  ]
  s.homepage = %q{http://github.com/runpaint/numb}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.4}
  s.summary = %q{Experiments in number theory with new predicate methods for Integer.}
  s.test_files = [
    "spec/emrip_spec.rb",
     "spec/polite_spec.rb",
     "spec/square_free_spec.rb",
     "spec/perfect_spec.rb",
     "spec/parasitic_spec.rb",
     "spec/hilbert_spec.rb",
     "spec/digital_sum_spec.rb",
     "spec/abundant_spec.rb",
     "spec/triangular_spec.rb",
     "spec/mobius_spec.rb",
     "spec/extravagant_spec.rb",
     "spec/achilles_spec.rb",
     "spec/perfect_power_spec.rb",
     "spec/practical_spec.rb",
     "spec/undulating_spec.rb",
     "spec/square_spec.rb",
     "spec/keith_spec.rb",
     "spec/narcissistic_spec.rb",
     "spec/trimorphic_spec.rb",
     "spec/factorion_spec.rb",
     "spec/carol_spec.rb",
     "spec/factor_spec.rb",
     "spec/economical_spec.rb",
     "spec/nivenmorphic_spec.rb",
     "spec/maris_mcgwire_sosa_pair_spec.rb",
     "spec/equidigital_spec.rb",
     "spec/powerful_spec.rb",
     "spec/dihedral_prime_spec.rb",
     "spec/frugal_spec.rb",
     "spec/kynea_spec.rb",
     "spec/number_of_prime_factors_spec.rb",
     "spec/weird_spec.rb",
     "spec/politeness_spec.rb",
     "spec/sphenic_spec.rb",
     "spec/automorphic_spec.rb",
     "spec/self_descriptive_spec.rb",
     "spec/polydivisible_spec.rb",
     "spec/number_of_distinct_prime_factors_spec.rb",
     "spec/vampire_spec.rb",
     "spec/semi_perfect_spec.rb",
     "spec/self_spec.rb",
     "spec/smarandache_wellin_spec.rb",
     "spec/dudeney_spec.rb",
     "spec/deficient_spec.rb",
     "spec/happy_spec.rb",
     "spec/hyperperfect_spec.rb",
     "spec/kaprekar_spec.rb",
     "spec/semiprime_spec.rb",
     "spec/smith_spec.rb",
     "spec/spec_helper.rb",
     "spec/harshad_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
